### ISSUE TITLE
New td+td2 Hacks?

### ISSUE THREAD

**Issue by ExampleAcc** [swagging-post/Blooket-Cheat-GUI#1]
Some hacks that I think would be really cool if they were to be added are like editing a towers stats like reload, ghost detection, damage, and addition buffs (In both versions). And it might also be cool if we could have a auto sell towers(basically clearing the map of all towers you own). And place anywhere on td2, and maybe trigger event in the hosted version. Please let me know if these are possible to make as I would really love if they were added.

**Comment by ExampleAcc** [comment]
Also I might not respond on this account as it is a temporary account and I'll probably respond on my main (idkbrolool).

**Comment by ExampleAcc** [comment]
also if possible a size adjuster for the gui

**Comment by swagging-post** [comment]
thanks for the suggestion, i'll try to add all of these if possible
