### ISSUE TITLE
not an issue, a question.

### ISSUE THREAD

**Issue by Egduffuu** [swagging-post/Blooket-Cheat-GUI#11]
@swagging-post, can i make the hack a script on tampermonkey/greasyfork? i will give full credit and give you the link. 
if not, its okay. i just feel like it could maximise the popularity of the hack. we could add the link to the github in the desc.

**Comment by swagging-post** [comment]
def if you want to, i wouldn't mind at all! and btw give yourself some credit for converting the script to a userscript.

**Comment by Egduffuu** [comment]
thanks!

**Comment by MikeKonz** [comment]
Btw this is 005Konz code so you are skidding and giving mis-information credit

**Comment by Egduffuu** [comment]
no he isn't. konz let him
