### ISSUE TITLE
stop skidding please

### ISSUE THREAD

**Issue by HallowedSpace** [swagging-post/Blooket-Cheat-GUI#17]
stop stealing cheats from konz and other devs and take down this repo, there already repos on and off this platform and there is no need to reupload and "fixing them" when you are just ripping them from the original repo and editing the little bit of text for attribution purposes with full intent of claiming them as your own when this is not the case. I assume the reason you do not offer unobfuscated versions of your "fixed" hack is because you simply stole from these notable developers and it also is seemingly strange how the "fixed gui" is exactly like the original gui made by konz. Even the README looks skidded as it looked exactly the same as the one from konz. Overall, just stop stealing dude. Just because you are boosting your GitHub stats by skidding doesn't mean you are cool by doing this. I know you have potential and its being wasted on this. Want to make cheats for blooket? Do something original and don't leech off of other developers to only attribute their contributions to yourself, script kiddie.

**Comment by swagging-post** [comment]
stfu

**Comment by swagging-post** [comment]
also ithe GUI is diff it's got GitHub not discord lol
