### ISSUE TITLE
Can you add Simulate Unlock

### ISSUE THREAD

**Issue by Obvious6123** [swagging-post/Blooket-Cheat-GUI#21]
I really want that feature since it was part of hacks

**Comment by swagging-post** [comment]
Working on it for V1.4!

**Comment by Obvious6123** [comment]
Thanks!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Obvious6123** [comment]
Also can you try to make it when you unlock all the blooks so you can also sell them, Because I don’t know if it is possible since the data cannot be saved to the backend of Blooket but it would be cool if it worked, (you don’t have to do it if you don’t want to btw)
Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Obvious6123** [comment]
question: is there a way to make the webpack work because someone has simulate unlock and they cannot fix webpack
