### ISSUE TITLE
Answer my 3 questions pls. I'm on mobile btw

### ISSUE THREAD

**Issue by Spideyboyjk** [swagging-post/Blooket-Cheat-GUI#5]
1) does it work for mobile

2) github ain't loading any of the code :/

3) ur the best

**Comment by Spideyboyjk** [comment]
Oh yeah one more thing is a (all answer correct) and (highlight correct answers) hacks on it?

**Comment by Egduffuu** [comment]
yes, and watch a bookmarklet tutorial to learn how to add on mobile.

**Comment by Spideyboyjk** [comment]
Alright ty
