### ISSUE TITLE
just a quik  question

### ISSUE THREAD

**Issue by Egduffuu** [swagging-post/Blooket-Cheat-GUI#7]
can you sell the blooks in get  all blooks. that would be OP.

**Comment by Egduffuu** [comment]
???

**Comment by DUBle-07** [comment]
Yesss plssss

**Comment by swagging-post** [comment]
Don't think so, because the acc you made for Blooket holds the Blooks in the backend, which with bookmarks makes it impossible, since it only can do frontend.
